name: Run on Upload

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@43
      - name: Run a Script After Upload
      - run: echo "Code was just uploaded !"
